services:
  api:
    build:
      context: ..
      dockerfile: capturit-payment-service/Dockerfile
    ports:
      - "3006:4005"
    environment:
      NODE_ENV: production
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
      STRIPE_WEBHOOK_SECRET: ${STRIPE_WEBHOOK_SECRET}
    stdin_open: true
    tty: true
